### PR TITLE
devel - Races

### PR DESCRIPTION
**Pull request by ttocsneb**
I have added races to the handbook.

The races use Character Race Table II and III.

The starting stats are limited to the race's limits but is bypassed when using setstat

The Race level limits are implemented to the table, but the exceptions directly below are too complex to implement.

### CODE REVIEW

**Comment by TheVoiceInsideYourHead** [comment]
!Levelup skips levels, not a priority as !setlevel works in its stead.

**Comment by TheVoiceInsideYourHead** [comment]
!Setrace acts funny if a class isn't chosen yet. Not a priority, can be worked around.

**Comment by TheVoiceInsideYourHead** [comment]
The file containing the character data sometimes becomes corrupted, and the bot can't handle it, so it freezes.

**Comment by ttocsneb** [comment]
!levelup is treated differently if the class has a max level

**Comment by ttocsneb** [comment]
This will not be merged, at least not yet.

**Pull request closed without merging**
